# Generated by Django 2.2.4 on 2019-08-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default=None, max_length=255)),
                ('majortype', models.CharField(default=None, max_length=255)),
                ('minortype', models.CharField(default=None, max_length=255)),
                ('value', models.CharField(default=None, max_length=500)),
            ],
            options={
                'db_table': 'media_dict',
            },
        ),
    ]
