# Generated by Django 2.2.4 on 2019-08-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meizifilter', '0002_mediadate_domain'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mediadate',
            table='media_dictr',
        ),
    ]
