# Generated by Django 2.2.4 on 2019-08-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meizifilter', '0003_auto_20190825_0847'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mediadate',
            table='media_dict',
        ),
    ]
