# Generated by Django 2.2.4 on 2019-08-30 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meizifilter', '0004_auto_20190825_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testone', models.CharField(default=None, max_length=200)),
                ('testtwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meizifilter.MediaDate')),
            ],
            options={
                'db_table': 'test_relation',
            },
        ),
    ]
