# Generated by Django 2.2.4 on 2019-08-30 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meizifilter', '0005_testrelation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestRelation',
        ),
    ]
