# Generated by Django 2.2.4 on 2019-09-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meizifilter', '0006_delete_testrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediadate',
            name='domain',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mediadate',
            name='minortype',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
